build-depends-android.sh support newer versions of NDK.
Minimum API level changed to 16 from 14. Define -D__ANDROID_API__ to choose correct
API level in unified headers. Fixes undefined reference to 'stdout'.